name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE]: "
labels: ["enhancement"]
assignees:
  - soporteghelo
body:
  - type: markdown
    attributes:
      value: |
        Gracias por sugerir una nueva funcionalidad! Tu idea es valiosa para el proyecto.

  - type: textarea
    id: problem
    attributes:
      label: ¿Tu feature request está relacionado con un problema? Describe.
      description: Una descripción clara y concisa de cuál es el problema.
      placeholder: ej. Me frustra cuando [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe la solución que te gustaría
      description: Una descripción clara y concisa de lo que quieres que pase.
      placeholder: ej. Quiero poder [...]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternativas que has considerado
      description: Una descripción clara y concisa de cualquier solución alternativa o funcionalidad que has considerado.
      placeholder: ej. He considerado [...]
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Contexto adicional
      description: Agrega cualquier otro contexto o screenshots sobre el feature request aquí.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Prioridad
      description: ¿Qué tan importante es esta funcionalidad para ti?
      options:
        - Baja
        - Media
        - Alta
        - Crítica
      default: 1
    validations:
      required: true